DROP DATABASE IF EXISTS nodesql;;
CREATE DATABASE nodesql;

USE nodeSQL;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NULL,
  country VARCHAR(100) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  auth_provider VARCHAR(50) NOT NULL DEFAULT 'local', 
  google_id VARCHAR(255) NULL , 
  picture VARCHAR(255) NULL
);
