DROP DATABASE IF EXISTS nodesql;
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
CREATE DATABASE nodesql;

USE nodeSQL;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NULL,
  country VARCHAR(100) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  auth_provider VARCHAR(50) NOT NULL DEFAULT 'local', 
  google_id VARCHAR(255) NULL UNIQUE
);
